### PR TITLE
Fixed link to Svelte website

### PR DESCRIPTION
**Pull request by bjorn**

### CODE REVIEW

**Review by RivarolaNicolas — APPROVED** [review]

**Comment by RivarolaNicolas** [comment]
Thank you for contributing to Simple Signer! 🙌 We missed that link.

**Comment by Ja-boop** [comment]
Hello, thanks for your contribution, you need to create a new actions secret in your repo settings, as SIMPLE_SIGNER_PRIVATE_KEY, then you should add any secret key from testnet and the test will pass through correctly

main.yml
image

We will clarify this in the documentation.

**Comment by fsodano** [comment]
@bjorn thank you for your contribution! We're going to try a workaround on our end to cater for PR's from forks + secret management. You don't have to do anything else, we'll get it merged :) thanks.

**Comment by bjorn** [comment]
For now I have nothing further to contribute unfortunately. Maybe when my SCF project gets funding I'll be looking to integrate Simple Signer. :-)

Regarding documentation changes like this, there's also the option to exclude them from the workflow, though I guess that won't help if the workflow is required to be run before merging.

**Pull request merged**
